# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 05:37
from __future__ import unicode_literals

from django.db import migrations


def update_slugs(apps, schema_editor):
    import random
    ContestModel = apps.get_model("trans", "Contest")

    for instance in ContestModel.objects.all():
        instance.slug = '%s_%s' % (instance.title.lower().replace(" ", ""), instance.id)
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0002_auto_20170512_0529'),
    ]

    operations = [
        migrations.RunPython(update_slugs, reverse_code=migrations.RunPython.noop)

    ]
