# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 05:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0003_auto_20170512_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 5, 48, 31, 49055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 5, 48, 31, 52323, tzinfo=utc)),
        ),
    ]
