# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0005_auto_20170526_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='enabled',
            new_name='public',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='task',
            name='uploaded_file',
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 2, 8, 28, 316535, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 2, 8, 28, 319728, tzinfo=utc)),
        ),
    ]
