# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0006_auto_20170528_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 14, 26, 55, 292455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 14, 26, 55, 296291)),
        ),
        migrations.AlterField(
            model_name='user',
            name='text_font_base64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='text_font_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 14, 26, 55, 295788, tzinfo=utc)),
        ),
    ]
