# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0007_auto_20170605_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='frozen',
        ),
        migrations.AddField(
            model_name='contest',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contest',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='content',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
