# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0008_auto_20170704_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None)),
                ('released', models.BooleanField(default=False)),
                ('release_note', models.CharField(blank=True, max_length=255)),
                ('saved', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.Translation')),
            ],
        ),
        migrations.RemoveField(
            model_name='contentversion',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='versionparticle',
            name='translation',
        ),
        migrations.DeleteModel(
            name='ContentVersion',
        ),
        migrations.DeleteModel(
            name='VersionParticle',
        ),
    ]
