# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-27 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0010_auto_20170727_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
