# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-04 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0012_auto_20180804_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='raw_password',
        ),
    ]
