# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-12 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0013_remove_user_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code2',
            field=models.CharField(null=True, default=None, max_length=255),
        ),
    ]
