# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0015_auto_20180819_0609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set([('user', 'task')]),
        ),
    ]
