# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-29 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0016_auto_20180822_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontest',
            name='extra_country1',
        ),
        migrations.RemoveField(
            model_name='usercontest',
            name='extra_country2',
        ),
    ]
