# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-23 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0018_translation_not_translating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='text_family',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
