# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-23 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0019_user_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontest',
            old_name='extra_country1',
            new_name='extra_country_1_code',
        ),
        migrations.RenameField(
            model_name='usercontest',
            old_name='extra_country1_count',
            new_name='extra_country_1_count',
        ),
        migrations.RenameField(
            model_name='usercontest',
            old_name='extra_country2',
            new_name='extra_country_2_code',
        ),
        migrations.RenameField(
            model_name='usercontest',
            old_name='extra_country2_count',
            new_name='extra_country_2_count',
        ),
    ]
