# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_job_queue', '0002_auto_20220618_2042'),
        ('trans', '0020_auto_20220423_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontest',
            name='final_print_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='print_job_queue.FinalPrintJob'),
        ),
    ]
