# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-24 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0021_usercontest_final_print_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='online',
        ),
    ]
