# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-30 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0022_remove_user_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontest',
            name='sealed',
            field=models.BooleanField(default=False),
        ),
    ]