# Generated by Django 5.0.6 on 2024-07-16 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_job_queue', '0004_auto_20220626_0413'),
        ('trans', '0024_alter_user_country_alter_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('on_site', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContestantContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usercontest',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.contest'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='unique_user_task'),
        ),
        migrations.AddConstraint(
            model_name='usercontest',
            constraint=models.UniqueConstraint(fields=('user', 'contest'), name='unique_user_contest'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.user'),
        ),
        migrations.AddField(
            model_name='contestantcontest',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.contest'),
        ),
        migrations.AddField(
            model_name='contestantcontest',
            name='contestant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.contestant'),
        ),
        migrations.AddField(
            model_name='contestantcontest',
            name='translation_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trans.user'),
        ),
        migrations.AddConstraint(
            model_name='contestantcontest',
            constraint=models.UniqueConstraint(fields=('contestant', 'contest'), name='unique_ctant_contest'),
        ),
    ]
