# Generated by Django 5.0.6 on 2024-07-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0026_contestants'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontest',
            name='skip_verification',
            field=models.BooleanField(default=False),
        ),
    ]
