# Generated by Django 5.0.6 on 2024-07-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0027_usercontest_skip_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='num_of_contestants',
        ),
        migrations.AddField(
            model_name='user',
            name='is_onsite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_translating',
            field=models.BooleanField(default=True),
        ),
    ]
