# Generated by Django 5.0.6 on 2024-07-22 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0028_remove_user_num_of_contestants_user_is_onsite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontest',
            name='extra_country_1_code',
        ),
        migrations.RemoveField(
            model_name='usercontest',
            name='extra_country_1_count',
        ),
        migrations.RemoveField(
            model_name='usercontest',
            name='extra_country_2_code',
        ),
        migrations.RemoveField(
            model_name='usercontest',
            name='extra_country_2_count',
        ),
        migrations.AlterField(
            model_name='contestantcontest',
            name='translation_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trans.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_onsite',
            field=models.BooleanField(default=True, help_text='User is present on-site (e.g., this allows printing)', verbose_name='Is on-site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_translating',
            field=models.BooleanField(default=True, verbose_name='Is translating'),
        ),
        migrations.AlterField(
            model_name='usercontest',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
