# Generated by Django 5.0.6 on 2024-08-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0030_alter_usercontest_final_print_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
