# Generated by Django 5.0.6 on 2025-07-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0031_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_translating',
        ),
    ]
