# Generated by Django 5.0.6 on 2025-07-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0032_remove_user_is_translating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('upload_translation_pdf', 'Staff member is allowed to upload translations as PDFs'), ('send_notifications', 'Send notifications to users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
