# Generated by Django 5.0.6 on 2025-07-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0033_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
