# Generated by Django 5.0.6 on 2025-07-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0034_contestant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontest',
            name='promised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercontest',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
