# Generated by Django 4.2.15 on 2024-09-04 15:30

from django.db import migrations

def sum_credit_and_usage(apps, schema_editor):
    UserTranslationQuota = apps.get_model('autotranslate', 'UserTranslationQuota')
    for obj in UserTranslationQuota.objects.all():
        obj.credit = obj.credit + obj.used
        obj.save()

def subtract_usage_from_credit(apps, schema_editor):
    UserTranslationQuota = apps.get_model('autotranslate', 'UserTranslationQuota')
    for obj in UserTranslationQuota.objects.all():
        obj.credit = obj.credit - obj.used
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('autotranslate', '0002_usertranslationquota_used'),
    ]

    operations = [
        migrations.RunPython(sum_credit_and_usage, subtract_usage_from_credit)
    ]
