# Generated by Django 5.0.6 on 2025-07-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotranslate', '0003_convert_remaining_credit_into_total_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGlassory',
        ),
    ]
