# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 19:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('interp', '0001_initial'), ('interp', '0002_auto_20170129_1832'), ('interp', '0003_auto_20170227_0741'), ('interp', '0004_auto_20170305_0619'), ('interp', '0005_auto_20170413_0631'), ('interp', '0006_auto_20170420_0821'), ('interp', '0007_auto_20170421_1143')]

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interp.Language')),
                ('task', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interp.Task')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interp.Country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interp.Language')),
                ('font', models.CharField(default='', max_length=255)),
                ('raw_password', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VersionParticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(default=None)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2017, 4, 21, 11, 43, 19, 358943, tzinfo=utc))),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interp.Translation')),
            ],
        ),
        migrations.AddField(
            model_name='translation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interp.User'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('title', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(verbose_name='Date Created')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='abbreviation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='rtl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 4, 21, 11, 43, 19, 355633, tzinfo=utc))),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('change_log', models.CharField(blank=True, max_length=255)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='text',
        ),
        migrations.AddField(
            model_name='translation',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
