# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 22:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interp.Language')),
                ('task', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interp.Task')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=255)),
                ('rtl', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interp.Country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interp.Language')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2017, 1, 28, 22, 31, 56, 499273))),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interp.Translation')),
            ],
        ),
        migrations.CreateModel(
            name='VersionParticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(default=None)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2017, 1, 28, 22, 31, 56, 499830))),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interp.Translation')),
            ],
        ),
        migrations.AddField(
            model_name='translation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interp.User'),
        ),
    ]
