# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 21:15
from __future__ import unicode_literals

from django.db import migrations

from django.core.management import call_command

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'countries.json', app_label='interp')
    call_command('loaddata', 'languages.json', app_label='interp')
    call_command('loaddata', 'translators.json', app_label='interp')


def unload_fixture(apps, schema_editor):
    # TODO: should be more specific
    call_command('flush')


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0001_squashed_0007_auto_20170421_1143'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
