# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-01 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='question',
            new_name='translation',
        ),
        migrations.AddField(
            model_name='version',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 1, 9, 50, 16, 256606)),
        ),
        migrations.AddField(
            model_name='version',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 1, 9, 50, 16, 257151)),
        ),
        migrations.AddField(
            model_name='versionparticle',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='versionparticle',
            name='translation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='interp.Translation'),
            preserve_default=False,
        ),
    ]
