# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0002_question_origques'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rtl',
            field=models.BooleanField(default=False),
        ),
    ]
