# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0002_load_intial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 21, 26, 57, 81567, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 21, 26, 57, 84729, tzinfo=utc)),
        ),
    ]
