# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0002_auto_20170101_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='version',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 3, 7, 32, 21, 423127)),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 3, 7, 32, 21, 423698)),
        ),
    ]
