# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0002_auto_20170129_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='abbreviation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='rtl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='font',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='version',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 27, 7, 41, 57, 328494)),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 27, 7, 41, 57, 329115)),
        ),
    ]
