# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 06:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0003_auto_20170227_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rtl',
        ),
        migrations.AlterField(
            model_name='version',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 5, 6, 19, 41, 718095)),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 5, 6, 19, 41, 718611)),
        ),
    ]
