# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0003_auto_20170421_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contest',
            field=models.CharField(default='Day 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 18, 55, 55, 740618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 18, 55, 55, 744011, tzinfo=utc)),
        ),
    ]
