# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0004_auto_20170428_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('content', models.TextField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 19, 51, 18, 294138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 19, 51, 18, 302066, tzinfo=utc)),
        ),
    ]
