# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interp', '0004_auto_20170305_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 4, 13, 6, 31, 49, 426152))),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='version',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='text',
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 13, 6, 31, 49, 428984)),
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
