# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0005_auto_20170428_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 19, 58, 46, 484193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='slug',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 19, 58, 46, 487323, tzinfo=utc)),
        ),
    ]
