# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0005_auto_20170413_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='change_log',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 8, 21, 40, 201379, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 8, 21, 40, 204187, tzinfo=utc)),
        ),
    ]
