# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0006_auto_20170420_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 11, 43, 19, 355633, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 11, 43, 19, 358943, tzinfo=utc)),
        ),
    ]
