# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0006_auto_20170428_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='font',
        ),
        migrations.AddField(
            model_name='user',
            name='text_font_base64',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 23, 1, 16, 792754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 23, 1, 16, 796008, tzinfo=utc)),
        ),
    ]
