# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interp', '0007_auto_20170428_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 11, 4, 52, 698276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='contest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interp.Contest'),
        ),
        migrations.AlterField(
            model_name='versionparticle',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 11, 4, 52, 702170, tzinfo=utc)),
        ),
    ]
