# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-25 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_job_queue', '0003_auto_20220626_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftprintjob',
            name='owner_country',
            field=models.CharField(blank=True, default='Nowhere', max_length=25),
        ),
        migrations.AddField(
            model_name='finalprintjob',
            name='owner_country',
            field=models.CharField(blank=True, default='Nowhere', max_length=25),
        ),
    ]
