# Generated by Django 5.0.6 on 2024-07-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_job_queue', '0005_worker_remove_printeddraftdocument_job_and_more'),
        ('trans', '0030_alter_usercontest_final_print_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalPrintJob',
        ),
        migrations.DeleteModel(
            name='PrintedFinalDocument',
        ),
    ]
