# Generated by Django 5.0.6 on 2024-08-28 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_job_queue', '0006_delete_finalprintjob_delete_printedfinaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printeddocument',
            name='file_path',
            field=models.FilePathField(match='.*.pdf', recursive=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='job_type',
            field=models.IntegerField(choices=[(0, 'DRAFT'), (1, 'FINAL')]),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='print_job_queue.worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='modulo',
            field=models.PositiveIntegerField(help_text='\n            If modulo is non-zero, this worker is restricted to jobs whose user ID\n            is equal to index modulo the given number.\n        '),
        ),
        migrations.AlterField(
            model_name='worker',
            name='server_print',
            field=models.BooleanField(help_text='Allow printing on the server.'),
        ),
    ]
