# Generated by Django 5.0.6 on 2024-09-03 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_job_queue', '0007_alter_printeddocument_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='printjob',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
